name: R-type CI
run-name: R-TYPE compilation
on: [push]
#   push:
#     branches:
#       - 'master'
#   pull_request:
#     branches:
#       - 'master'
jobs:
  R-type_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build R-Type
        run: ./install.sh

      - name: Create linux binaries artifacts for Github
        uses: actions/upload-artifact@v3
        with:
          name: Linux_deliverable
          path: bin/linux

  R-type_windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build R-Type
        run: .\install.bat

      - name: Create windows binaries artifacts for Github
        uses: actions/upload-artifact@v3
        with:
          name: Windows_deliverable
          path: bin/windows